language: objective-c
osx_image: xcode6.4
branches:
  only:
    - master
xcode_project: ReadyForCoffee.xcodeproj
xcode_scheme: ReadyForCoffeeTravis
before_install:
  - brew update; brew update
  - brew install carthage
  - carthage build